name = "basis-signal"
main = "src/index-signal.ts"
compatibility_date = "2024-04-01"

# TODO: Add BASIS_WALLET_ADDRESS as a secret using:
# wrangler secret put BASIS_WALLET_ADDRESS

# TODO: Add BASIS_PRIVATE_KEY as a secret using:
# wrangler secret put BASIS_PRIVATE_KEY

# KV Namespace for Risk Database (High-speed Risk Storage)
[[kv_namespaces]]
binding = "RISK_KV"
id = "a76c3f854f3f48a6ab528081e30f6518"
preview_id = "753c1ce2f77f48e7b5253725d8d02932"

